#
# .bashrc
#
# Notice that because this set of files contains settings for setting up a
# standalone nix configuration, the paths defined here should be modified for
# the system you are working for.
#

# For nix settings
export NP_RUNTIME=bwrap
export NP_LOCATION=/uscms_data/d3/yimuchen/nix-setup/ 
export PATH=/uscms_data/d3/yimuchen/nix-setup:$PATH
alias nix-zsh-shell="nix-portable nix shell --offline 'nixpkgs#nix' 'nixpkgs#zsh' 'nixpkgs#tmux' --command zsh -l"

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

