" .vimrc

""----  Indention settings  ----------------------------------------------------
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent

""----  Search settings  -------------------------------------------------------
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase

""----  Number column settings  ------------------------------------------------
set number
set relativenumber
set numberwidth=4

""----  Misc. Settings  --------------------------------------------------------
set showcmd
set backspace=2
set formatoptions=c,q,r,t
set ruler
set background=dark
set mouse=a
set shell=zsh\ --login

""----  Spell check settings  --------------------------------------------------
set spell spelllang=en_gb
syntax spell toplevel
