local endpoint = "http://localhost:11434"
if vim.uv.os_gethostname() == "enscFramework" then
  endpoint = "http://100.101.178.17:11434"
end

return {
  -- {
  --   "yetone/avante.nvim",
  --   build = function()
  --     return "make BUILD_FROM_SOURCE=true"
  --   end,
  --   event = "VeryLazy",
  --   version = false, -- Never set this value to "*"! Never!
  --   ---@module 'avante'
  --   ---@type avante.Config
  --   opts = {
  --     provider = "ollama",
  --     providers = {
  --       ollama = {
  --         endpoint = endpoint,
  --         model = "gpt-oss:20b",
  --       },
  --     },
  --   },
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     --- The below dependencies are optional,
  --     "hrsh7th/nvim-cmp",
  --     "nvim-tree/nvim-web-devicons",
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { "markdown", "Avante" },
  --       },
  --       ft = { "markdown", "Avante" },
  --     },
  --   },
  -- },
  -- {
  --   'milanglacier/minuet-ai.nvim',
  --   config = function()
  --     require('minuet').setup {
  --       provider = 'openai_fim_compatible',
  --       n_completions = 1, -- Recommended for local model for resource saving
  --       context_window = 1024,
  --       provider_options = {
  --         openai_fim_compatible = {
  --           api_key = 'TERM',
  --           name = 'Ollama',
  --           end_point = endpoint .. '/v1/completions',
  --           model = 'gpt-oss:20b',
  --           optional = { max_tokens = 1024, top_p = 0.9 },
  --         },
  --       },
  --       virtualtext = {
  --         auto_trigger_ft = {},
  --         keymap = {
  --           accept = '<A-A>',
  --           accept_line = '<A-a>',
  --           accept_n_lines = '<A-z>',
  --           prev = '<A-[>',
  --           next = '<A-]>',
  --           dismiss = '<A-e>',
  --         },
  --       },
  --     }
  --   end,
  -- }
}
