#!/usr/bin/env bash
# Environment variables
if [[ -r /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh ]] ; then
 source "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh"
elif [[ -r $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh ]] ; then
 source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
fi

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
fi

if [[ -z "${DOMAIN_NAME}" ]]; then
  if command -v domainname 2>&1 >/dev/null
  then
      export DOMAIN_NAME=$(domainname -d)
   fi
fi

export PATH="$PATH:$HOME/.config/dot-bin/common/"
export EDITOR="nvim"
export MAMBA_ROOT_PREFIX="$HOME/.mamba"
export MACHINE_TYPE_SIMPLE=""
export MACHINE_TYPE_DETAIL=""

# Local configurations for personal machines
if [[ "$HOST" == "ensc"* ]]; then
  export PATH="$PATH:$HOME/.config/dot-bin/local/"
  export KRB5CCNAME="DIR:${HOME}/.temp.persist"
  export MACHINE_TYPE_SIMPLE="local"
# Common configurations for remote machines
  export MACHINE_TYPE_DETAIL="personal"
else
  if [[ -d $HOME/.nix-profile/bin ]] ; then
    export PATH=$HOME/.nix-profile/bin/:$PATH
    export SSL_CERT_FILE="$HOME/.nix-profile/etc/ssl/certs/ca-bundle.crt"
  fi
  if [[ -d "/cvmfs/cms.cern.ch" ]]; then
    export PATH="$PATH:$HOME/.config/dot-bin/remote/cmssw/"
  fi
  export PATH="$PATH:$HOME/.config/dot-bin/remote/"
  export MACHINE_TYPE_SIMPLE="remote"

  if [[ -z $LANG ]]; then
    export LANG="en_US.UTF-8"
  fi
fi


# Machine specific path settings
if [[ "$HOST" == "hepcms"* ]]; then
  export CMSSW_APPTAINER_BINDPATH="/data,/data2"
  export MACHINE_TYPE_DETAIL="umdcms"
elif [[ "$HOST" == "cmslpc"* ]]; then
  export CMSSW_APPTAINER_BINDPATH="/uscms,/uscmst1b_scratch,/cvmfs,/cvmfs/grid.cern.ch/etc/grid-security:/etc/grid-security,/uscms_data"
  export LARGE_STORAGE_DIR="/uscms_data/d3/yimuchen"
  export MACHINE_TYPE_DETAIL="cmslpc"
elif [[ "$HOST" == "lxplus"* && "$DOMAIN_NAME" == "cern.ch" ]]; then
  export LARGE_STORAGE_DIR="/afs/cern.ch/work/y/yichen"
  export MACHINE_TYPE_DETAIL="lxplus"
elif [[ "$DOMAIN_NAME" == "etp.kit.edu" ]]; then # KIT RELATED MACHINES
  export CMSSW_APPTAINER_BINDPATH="/ceph,/work,/home,/cvmfs/grid.cern.ch/etc/grid-security:/etc/grid-security,/etc/condor,/var/lib/condor"
  export LARGE_STORAGE_DIR="/work/ychen";
  export MACHINE_TYPE_DETAIL="kit"
fi # Don't do anything for unrecognized machines


