# ZSHRC
#
# Notice that ~/.zshrc is only involved in the interactive session of zsh (i.e.
# zsh session that was spawned with `zsh -l` or similar, to ensure that custom
# shell functions can also be used in single-instance shell interactions (such
# as calling shell functions within shell function neovim and tmux), the PATH
# variable should be modified in the ~/.zshenv file instea 



####### Uncomment to enable profiling
# zmodload zsh/zprof
######

# Instant prompt for powerlevel10k
if [[ -r "$HOME/.cache/p10k-instant-prompt-${USER}.zsh" ]]; then
  source "$HOME/.cache/p10k-instant-prompt-${USER}.zsh"
fi

typeset -U path cdpath fpath manpath

if [[ $USER == "ensc" ]] ; then
  for profile in ${(z)NIX_PROFILES}; do
    fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
  done
elif [[ -d $HOME/.nix-profile ]]; then
  profile=$HOME/.nix-profile
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
fi


# HELPDIR=$(realpath "$(dirname $(realpath $(which zsh)))/../share/zsh/$ZSH_VERSION/help")

# Installing the antidote plugin manager if it doesn't exist
export ANTIDOTE_HOME=$HOME/.local/share/antidote_plugins
if [[ ! -d $HOME/.local/share/antidote ]] ; then
  git clone --depth=1 https://github.com/mattmc3/antidote.git $HOME/.local/share/antidote
fi
source $HOME/.local/share/antidote/antidote.zsh
# We will explicitly not be using the static version of antidote plugins to
# better improve portability
antidote load $HOME/.config/zsh/zsh_plugins.txt

# Enabling the autocomplete script. This is very slow on Nix systems so setting
# this to only run once per day
autoload -Uz compinit
if [[ $(($(date +%s) - $(stat -c "%Y" $HOME/.zcompdump))) -gt 86400 ]]; then
  compinit
else
  compinit -C
fi

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

# FZF integration
eval "$(fzf --zsh)"

# Setting the theme of the prompt
source "$HOME/.config/zsh/p10k.zsh"
# Additional command-line tools that uses common gnu-coreutils tools
source "$HOME/.config/zsh/common_utils.sh"
# Additional settings for specific machines (must be loaded after the p10k configuration)
source "$HOME/.config/zsh/machine.sh"

############## Uncomment to run profiling
# zprof
########
