channels:
  - conda-forge
  - defaults
dependencies:
  - ruff-lsp
  - python-lsp-server
  - ipython
  - ipykernel
  - pip
  - pip:
    - pynvim # For REPL interaction
    - mdformat # For notebook editing in nvim
    - mdformat-frontmatter
    - jupytext
